apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: redditprocessor
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python-39
    namespace: ""
  functionTimeout: 600
  idletimeout: 120
  package:
    functionName: redditProcessor.main
    packageref:
      name: redditprocessor
      namespace: ""
  requestsPerPod: 1
  resources: {}
