include:
- ./redditprocessor.zip
kind: ArchiveUploadSpec
name: redditprocessor-zip-bJVt

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: redditprocessor
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python-39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://redditprocessor-zip-bJVt
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-14T04:13:04Z"
