include:
- ./addreddit.zip
kind: ArchiveUploadSpec
name: addreddit-zip-fKZS

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: addreddit
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://addreddit-zip-fKZS
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-11T17:42:14Z"
