include:
- ./rharvester.zip
kind: ArchiveUploadSpec
name: rharvester-zip-qC92

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: rharvester
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://rharvester-zip-qC92
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-13T08:44:13Z"
