include:
- ./enqueue/__init__.py
- ./enqueue/enqueue.py
- ./enqueue/requirements.txt
- ./enqueue/build.sh
kind: ArchiveUploadSpec
name: enqueue---init---py-Onqc

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: enqueue
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://enqueue---init---py-Onqc
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-12T04:07:59Z"
